= Off-heap
By Thomas SCHWENDER
:icons: font
// check https://github.com/Ardemius/personal-wiki/wiki/AsciiDoctor-tips for tips on table of content in GitHub
:toc: macro
:imagesdir: images
:source-highlighter: highlightjs
// the following attributes are specific to the DZSlides backend
:backend: dzslides
:dzslides-style: stormy
:dzslides-transition: fade
:dzslides-fonts: family=Yanone+Kaffeesatz:400,700,200,300&family=Cedarville+Cursive
:dzslides-highlight: monokai

// No preamble, and so, no table of contents accepted in DZSlides. Put in comments the following lines if generating slides with this backend
One document type to handle them all! (documents, blogs, slides, books, etc.)

toc::[]

== Exemple d'utilisation : ActivePivot

* ActivePivot : base de données en mémoire, écrite en Java, très grosse volumétrie, très fortes contraintes de performance +

=== Intérêts

Permet d'outrepasser certaines contraintes inhérentes à Java :

* pas fait pour gérer de très fortes volumétries de données
* le GC n'est pas réellement fait pour gérer des objets +
Pour rappel les fonctions du GC sont :
** de détecter les objets qui ne sont plus référencés (utilisés), et de les effacer
** de déplacer les survivants d'une zone mémoire à l'autre afin de libérer de la place pour l'affectation des nouveaux objets
Cela convient bien à des objets dont le cycle de vie est court, et pour des JVM de l'ordre de quelques Go.

Par contre, ce principe ne semble pas adapté à des objets lourds et à cycle de vie long. +
Ces derniers vont en effet être régulièrement déplacés d'une zone mémoire à l'autre, ce qui va être d'autant plus pénalisant que les objets sont lourds, et que l'opération de déplacement du GC est bloquante (*VERIFIER DANS QUELS CAS EXACTEMENT*)

Une solution : sauvegarder les données dans une zone mémoire non gérée par le GC (appelée mémoire Off-Heap)

=== Comment allouer de la mémoire Off-Heap

Cela passe par l'utilisation de `java.nio.ByteBuffer`.

Les objets instanciés à partir de cette classe vont être stockés dans la Heap. +
Par contre, il va s'agir de "pointeurs", très légers en eux-mêmes, vers une zone mémoire en dehors de la Heap.

Manipuler le contenu de ces objets n'est pas sans contraintes :

* ce contenu n'est accessible que par le principe de sérialisation / désérialisation. +
En effet, ce que Java va stocker dans la mémoire off-heap va être considéré comme des octets, et non des objets.

== Resources

* http://www.touilleur-express.fr/2015/01/14/parisjug-soiree-youngblood/ +
Sujet 3 : Faire tourner une JVM avec 4 To de mémoire : yes we can par Gaëlle Guimezanes
Travaille chez QuartetFS, éditeur d'ActivePivot, solution d'analyse multidimensionnelle +
Voir la vidéo https://www.youtube.com/watch?v=Cskt4qtNeEI
* se renseigner sur `sun.misc.Unsafe`
* http://blog.ippon.fr/2011/11/03/java-acces-directs-a-la-memoire-off-heap/
* https://docs.oracle.com/javase/8/docs/api/java/nio/ByteBuffer.html[java.nio.ByteBuffer] : surtout la section _Direct vs. non-direct buffers_


  